# config.yml

input_atoms: 0
d_model: 512
num_heads: 8
encoder_layers: 3
decoder_layers: 3
hidden_linear_dim: 1024

# Training settings
train_val: 0.75
val_test: 0.5
epochs: 50
switch_batch: 0.1
batch_size: 32
learning_step: 0.00005
dropout: 0.1
label_smoothing: 0.1
num_inputs: 4096
loss_type: "mean"

# Label smoothing and noise settings
min_lbl_smooth_mean: 0.75
max_lbl_smooth_mean: 0.95
min_lbl_smooth_stdev: 0.025
max_lbl_smooth_stdev: 0.25
min_noise_stdev: 0.1
max_noise_stdev: 0.2
final_stage_noise_stdev: 0.05

# Progressive learning parameters
progressive_learning_split: 0.8
cycles_split: 0.25
diffusion_cycles: 10

# Paths
out_path: "output"
loss_plot: "loss_vs_epoch.png"
seq_plot: "seq_sim_vs_epoch.png"
weights_path: "model_parameters.pth"
data_path: "/gpfs_backup/wangyy_data/protAI/pmpnn_data/pdb_2021aug02"
max_load: 8192
max_tokens: 5000