# Configuration for training the model
d_model: 512 # dimensionality of input embeddings
min_wl: 3.7  # minimum wl to use in wavelength sampling
max_wl: 20.0  # maximum wl to use in wavelength sampling
base_wl: 20.0  # minimum base to use in wavelength sampling
d_hidden_we: 1024
hidden_layers_we: 8

d_hidden_aa: 1024
hidden_layers_aa: 3
esm2_weights_path: "utils/model_utils/esm2/esm2_t33_650M_UR50D.pt"  # can be a path or the name of the esm2 model.
                                                                    # if the latter, fetched from facebook website
                                                                    # if not provided, fetches the best match from facebook based on d_model

encoder_layers: 4 # number of dualcoder layers
num_heads: 8  # number of attention heads to perform the training with
min_spread: 3.0
max_spread: 6.0
base_spread: 10.0
num_spread: 64
min_rbf: 0.01
max_rbf: 0.99
d_hidden_attn: 1024  # intermediate dimensions of decoder feed forward layer
hidden_layers_attn: 0

temperature: 0.1  # temperature for autoregressive inference (for testing)

# Training configuration
num_train: -1  # number of training samples to use; -1 means all available
num_val: -1  # number of validation samples to use; -1 means all available
num_test: -1  # number of test samples to use; -1 means all available
epochs: 100  # number of epochs

# want as few combinations as possible to speed up triton autotuning
max_batch_size: 256  # possible samples per batch
min_seq_size: 64 # possible sequence lengths
max_seq_size: 8192 # possible sequence lengths
batch_tokens: 8192 # number of valid tokens per batch 
min_resolution: 3.5

accumulation_steps: 1  # grad accumulation; how many batches to process before learning step
beta1: 0.9  # learning rate
beta2: 0.98  # learning rate
epsilon: 10e-9  # learning rate
dropout: 0.1  # percentage of dropout
label_smoothing: 0.1  # percentage of label smoothing to use on the output labels for loss calculation
loss_type: "mean"  # whether to use the 'sum' or the 'mean' for CEL
loss_scale: 2000
lr_type: plateau
lr_step: 5e-6  # learning rate
lr_initial_min: 5e-5
lr_initial_max: 1e-4
lr_final_min: 1e-5
lr_final_max: 5e-5
lr_cycle_length: 7.0

lr_scale: 0.1  # LR scaling factor
lr_patience: 100  # LR patience for scaling down after plateau
use_chain_mask: False # whether to mask all chains except the sequence cluster representative
use_amp: True  # whether to use automatic mixed precision

# ------------------------------------------------------------------------------

# Input MASK injection
initial_min_MASK_injection_mean: 0.15  # initial minimum mean percentage of MASK injection injection in training
final_min_MASK_injection_mean: 0.15  # final minimum mean percentage of MASK injection injection in training
initial_max_MASK_injection_mean: 0.15  # initial maximum mean percentage of MASK injection injection in training
final_max_MASK_injection_mean: 0.15  # final maximum mean percentage of MASK injection injection in training
MASK_injection_stdev: 0.00  # stdev percentage of MASK injection injection in training
MASK_injection_cycle_length: 20  # input MASK token injection cycle length

# ------------------------------------------------------------------------------

# Output
# out_path: "/share/wangyy/hjc2538/proteusAI/models/test"  # path to store output, such as plots and weights file. for nc state hpc
out_path: "/scratch/hjc2538/projects/proteusAI/models/test"  # path to store output, such as plots and weights file. for uncw hpc
loss_plot: "loss_vs_epoch.png"  # path to save plot of loss vs epochs after training
seq_plot: "seq_sim_vs_epoch.png"  # path to save plot of sequence similarity vs epochs after training
weights_path: "model_parameters.pth"  # path to save weights after training
write_dot: True  # whether to save the dot file of the computational graph

# Input
# data_path: "/share/wangyy/hjc2538/proteusAI/pdb_2021aug02_filtered"  # path to data for ncs hpc
data_path: "/scratch/hjc2538/projects/proteusAI/pdb_2021aug02_filtered"  # path to data for uncw hpc
# use_model: 
# early_stopping: 
# model_checkpoints:
config: "config/config.yml"  # Path to the YAML config file
